[workspace]
authors = ["conradolandia <andresconrado@gmail.com>"]
channels = ["conda-forge"]
name = "fontsampler"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "pyinstaller fontsampler.spec"
build-clean = "pyinstaller --noconfirm --clean fontsampler.spec"
build-debug = "pyinstaller --debug all fontsampler.spec"
build-install = {depends-on = ["build-simple"], cmd = "bash -c 'cp -fv dist/fontsampler $HOME/.local/bin/fontsampler'"}
build-simple = "pyinstaller --onefile --name fontsampler fontsampler.py"
install = {cmd = "bash -c 'cp -fv dist/fontsampler $HOME/.local/bin/fontsampler'"}

[dependencies]
fonttools = ">=4.59.0,<5"
pycairo = ">=1.28.0,<2"
pyinstaller = ">=6.8.0,<7"
weasyprint = ">=62.0,<63"
pygobject = ">=3.48.0,<4"
cairocffi = ">=1.6.0,<2"
