[workspace]
authors = ["conradolandia <andresconrado@gmail.com>"]
channels = ["conda-forge"]
name = "fontsampler"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "pyinstaller fontsampler.spec"
build-debug = "pyinstaller --debug all fontsampler.spec"
build-simple = "pyinstaller --onefile --name fontsampler fontsampler.py"
build-clean = "pyinstaller --noconfirm --clean fontsampler.spec"

[dependencies]
fonttools = ">=4.59.0,<5"
reportlab = ">=4.4.1,<5"
pillow = ">=11.3.0,<12"
pypdf2 = ">=3.0.1,<4"
pyinstaller = ">=6.8.0,<7"
