[workspace]
authors = ["conradolandia <andresconrado@gmail.com>"]
channels = ["conda-forge"]
name = "fontsampler"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
fonttools = ">=4.59.0,<5"
matplotlib = ">=3.10.3,<4"
reportlab = ">=4.4.1,<5"
pillow = ">=11.3.0,<12"
pypdf2 = ">=3.0.1,<4"
pip = ">=25.1.1,<26"
